# Generated by Django 5.2.7 on 2025-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_remove_player_first_name_remove_player_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
