# Generated by Django 5.2.7 on 2025-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_game_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sequence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
