# Generated by Django 5.2.7 on 2025-10-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_game_sequence_game_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='bingo.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
