# Generated by Django 5.2.7 on 2025-10-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_game_finished_game_winner_index_game_winner_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_index',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='won_at',
        ),
    ]
