# Generated by Django 5.2.7 on 2025-10-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_remove_game_winner_index_remove_game_winner_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('add', 'Entertainer Add'), ('set_adj', 'Entertainer Set Adjustment'), ('other', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actor_tid', models.BigIntegerField(blank=True, help_text='Telegram ID who initiated this transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bingo.player')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'kind'], name='bingo_trans_created_129a41_idx')],
            },
        ),
    ]
