# Generated by Django 5.2.7 on 2025-10-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stakes_charged',
            field=models.BooleanField(default=False),
        ),
    ]
