# Generated by Django 5.2.7 on 2025-10-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_game_stakes_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='charged_count',
            field=models.IntegerField(default=0),
        ),
    ]
