# Generated by Django 5.2.7 on 2025-10-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_game_charged_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
